[package]
name = "obsidian-bar"
version = "0.1.0"
edition = "2024"

[dependencies]
gio = { version = "0.22", features = ["v2_72"] }
gdk-pixbuf = "0.22"
async-channel = "2"
gtk = { package = "gtk4", version = "0.11", features = ["v4_10"] }
gtk4-layer-shell = "0.8"
niri-ipc = "=26.4.0"
pipewire = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
